repos:
  - repo: local
    hooks:
      - id: ruff
        name: ruff
        entry: ruff check
        language: system
        types: [python]
        args: ["--fix", "--config", "pyproject.toml", "--select", "E,F,I", "--ignore", "E501,E402"]
      - id: ruff-up
        name: ruff (UP)
        entry: ruff check
        language: system
        types: [python]
        args: ["--fix", "--config", "pyproject.toml", "--select", "UP", "--ignore", "E501,E402"]
      - id: ruff-b
        name: ruff (B)
        entry: ruff check
        language: system
        types: [python]
        args: ["--config", "pyproject.toml", "--select", "B", "--ignore", "B008,B904"]
      - id: ruff-sim
        name: ruff (SIM)
        entry: ruff check
        language: system
        types: [python]
        args: ["--config", "pyproject.toml", "--select", "SIM", "--ignore", "E501,E402,SIM105", "--fix"]
      - id: black
        name: black
        entry: black
        language: system
        types: [python]
        args: ["--line-length=100"]
