# ==============================================================================
# Backend Service
# ==============================================================================
apiVersion: v1
kind: Service
metadata:
  name: {{ include "bybit-strategy-tester.fullname" . }}-backend
  labels:
    {{- include "bybit-strategy-tester.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
  selector:
    {{- include "bybit-strategy-tester.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: backend
