version: "3"
services:
  backend:
    build: .
    command: python -m uvicorn backend.main:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PROMETHEUS_METRICS_PORT=8000
    depends_on:
      - redis
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/v1/live/health"]
      interval: 30s
      timeout: 5s
      retries: 3
  ws_publisher:
    build: .
    command: python -m backend.workers.ws_publisher --redis redis://redis:6379/0
    depends_on:
      - backend
      - redis
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001/metrics"]
      interval: 30s
      timeout: 5s
      retries: 3
    ports:
      - "8001:8001" # ws_publisher prometheus metrics
  redis:
    image: redis:6
    ports:
      - "6379:6379"
  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./deploy/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    ports:
      - "9090:9090"
